### ISSUE TITLE
Products Landing

### ISSUE THREAD

**Issue by acreilly** [curranabell/materialTheme#1]
Sorry, don't know how to ask you another way. Does your productsLanding work on tags/shop or just on the homepage?

**Comment by curranabell** [comment]
Hey Allie, message me on Gitter. It is the best way to reach me. Just put a reply in there but I will copy it here. "So basically you just need to modify the productGrid. I created a customProductGrid, added a sidebar for product filters, and then added some code at the bottom of the customProductGrid.js file to get it working. This is the code at the bottom you need to add

Template.customProductGrid.replaces("productGrid");
Template.customProductGrid.inheritsHelpersFrom("productGrid");
Template.customProductGrid.inheritsEventsFrom("productGrid");
Template.customProductGrid.inheritsHooksFrom("productGrid");

I pushed it to my materialTheme repo so you should be able to check it out. It is working.
The productsLanding repo just works on the shop page"

**Comment by acreilly** [comment]
Yup! Just figured it out a couple hours ago, thanks!
