### ISSUE TITLE
I have error when install theme.

### ISSUE THREAD

**Issue by vanloc0301** [curranabell/materialTheme#3]
I have error like:

> => Errors prevented startup:
>    While building for web.browser:
>    imports/plugins/included/default-theme/client/styles/layout.less:1: Unknown
>    import: {}/imports/plugins/included/default-theme/client/styles/main.less
>    
>    While processing files with less (for target web.browser):
>    client/plugins.less:8: Unknown import:
>    /imports/plugins/included/default-theme/client/index.less
>    
> => Your application has errors. Waiting for file change.
> => It looks like a simple tweak to your system's configuration will make many
>    tools (including this Meteor command) more efficient. To learn more, see
>    https://github.com/meteor/meteor/wiki/File-Change-Watcher-Efficiency

I am using for Reaction v1.3.0.

I clone your Repo to `/imports/plugins/included/default-theme/`

Update: I replace all file in your Repo to `/imports/plugins/included/default-theme/` and it's working.

But I see a blank screen in `localhost:3000`. Like this:

![screenshot_2017-06-30_10-01-02](https://user-images.githubusercontent.com/4168981/27719223-14acea92-5d7b-11e7-99b4-b73d77454c85.png)

**Comment by nonfungibletunji** [comment]
meteor add ultimatejs:tracker-react, had the same problem, this fixed it
